[FIX] sale_order_blanket_order: _action_launch_stock_rule take named parameters
`_action_launch_stock_rule` now takes its parameters named instead of positional.

Error message:
> TypeError: SaleOrderLine._action_launch_stock_rule() takes 1 positional argument but 2 were given

- Fixed bug by changing how paremeters are passed
- Existing tests detects the issue: no need to add another