sale_order_blanket_order: fix _compute_call_off_order_count
Error message:
  ValueError: Order term 'blanket_order_id.id' is not a valid aggregate nor valid groupby

Root Cause:
_compute_call_off_order_count crashes on 18 because `_read_group` is called the Odoo 16 way.

Fix:
order parameter in _read_group does not support .id anymore.
Removed order parameter as it's not useful to the function.

Added test reproducing call_off_order_count crash